### ISSUE TITLE
Зачем наллабл везде!

### ISSUE THREAD

**Issue by Shifu462** [Mishka1337/TestWebApiProject#2]
https://github.com/Mishka1337/TestWebApiProject/blob/4d2cf7417c1fe3b121bbc5e3eaf4e54988b3d809/WebApiTest/Models/Cardholder.cs#L7-L13

https://github.com/Mishka1337/TestWebApiProject/blob/4d2cf7417c1fe3b121bbc5e3eaf4e54988b3d809/WebApiTest/Models/Atm.cs#L5-L11

https://github.com/Mishka1337/TestWebApiProject/blob/4d2cf7417c1fe3b121bbc5e3eaf4e54988b3d809/WebApiTest/Models/Account.cs#L7
 
Зачем `int?`?
Типа, либо у тебя сколько-то денег, либо 0 денег. `null` это типа вообще пиздец?
 
Вот на всякий пожарный:
https://metanit.com/sharp/tutorial/2.17.php
https://referencesource.microsoft.com/#mscorlib/system/nullable.cs
 
Вообще, мега справедливо было бы влепить какой-нибудь `ushort` `uint` `ulong`, но кажется БД не поддерживает такие типы.

**Comment by Mishka1337** [comment]
ну нулбл в некоторых классах необходим для дб в энтити
когда например у кардхолдера нет купюр 
я может не до конца понял сути нулбл
но поастараюсь подправить !

**Comment by Shifu462** [comment]
@Mishka1337 
пусть, когда у кардхолдера нет купюр, это будет называться не "у кардхолдера null купюр", а "у кардхолдера 0 купюр"
