### ISSUE TITLE
не стоит хардкодить connection string

### ISSUE THREAD

**Issue by Shifu462** [Mishka1337/TestWebApiProject#3]
https://github.com/Mishka1337/TestWebApiProject/blob/4d2cf7417c1fe3b121bbc5e3eaf4e54988b3d809/WebApiTest/Startup.cs#L22-L23
 
https://stackoverflow.com/questions/45796776/get-connectionstring-from-appsettings-json-instead-of-being-hardcoded-in-net-co

**Comment by Mishka1337** [comment]
вот это просто красиво и по фатку конечно !
