### ISSUE TITLE
static Atm

### ISSUE THREAD

**Issue by Shifu462** [Mishka1337/TestWebApiProject#4]
https://github.com/Mishka1337/TestWebApiProject/blob/master/WebApiTest/Models/Atm.cs
 
А как сохраняться количество бабок в `Atm` будет? Поля с количеством бабок же тоже static, разумеется. А статик-классы не маппятся в дб.
В базе просто не существует таблицы с Atm-ами, поэтому после перезапуска приложухи у тебя снова будут в банкомате бабки, вне зависимости от того, сколько ты оттуда выкачал до перезапуска.

Хотя я понимаю, что это осознанный выбор:
https://github.com/Mishka1337/TestWebApiProject/blob/4d2cf7417c1fe3b121bbc5e3eaf4e54988b3d809/WebApiTest/Program.cs#L11-L14
 
Но, типа, банкоматов же существует много в мире. Захотел -- из одного снял, а захотел -- подошёл к другому, и он тебе зажал бабки, говорит нема.

**Comment by Mishka1337** [comment]
это пока костыль
конечно дбсет с одной строчкой будет)
