### ISSUE TITLE
Рефакторинг валидации

### ISSUE THREAD

**Issue by Shifu462** [Mishka1337/TestWebApiProject#7]
https://github.com/Mishka1337/TestWebApiProject/blob/4d2cf7417c1fe3b121bbc5e3eaf4e54988b3d809/WebApiTest/Models/Atm.cs#L13-L48
 
Переименуй во что-нибудь вроде `ValidateWithdrawalAmount`, `IsValidWithdrawalValue`. Он же проверяет на валидность именно бабки на вывод.
 
---

А вообще, пересмотри код. У тебя же прямое дублирование кода. Причём тут не только дублирование кода, но и повторные вычисления идут!
Этот метод валидации почти не отличается от метода `Atm.Withdraw` (разумеется, кроме того, что последний забирает бабки у автомата и даёт кардхолдеру реально).
Те же условные конструкции. И они вызываются друг за другом.
 
 
Предлагаю такое решение!
1. Выпиливаешь `Is_Valid_Value`
2. `void Atm.Withdraw` заменяешь на `bool TryWithdraw`
 
И этот `TryWithdraw` попытается вывести деньги и вернёт `true` или `false` в зависимости от того, провелась транзакция или нет.
В течение метода работаешь со скопированными полями `int Count100...Count5000` в локальные переменные `int count100-count5000`
- Если под конец метода `int value` (сумма вывода!) оказалась равна нулю, то заебись. Фиксируешь насчитанные `count100-count5000` и там и там (в атме и в кардхолдере и в аккаунте), возвращаешь `true`.
- Если `value != 0`, ничего не фиксируешь, возвращаешь `false`.
 
А в контроллере проверяешь этот `bool success = Atm.TryWithdraw(...)`, и если `!success`, то кидаешь `400 Bad Request`.
 
Так не будет никакого дублирования, расчёты расчитываются быстро, все счастливы!

**Comment by Mishka1337** [comment]
учту !
тоже смущало повторное повторение
